class Idioma:

    ATUAL = "pt"

    TEXTOS = {
        "pt": {
            # Comuns a várias telas
            "comum.id": "ID",
            "comum.nome": "Nome",
            "comum.novo": "Novo",
            "comum.salvar": "Salvar",
            "comum.alterar": "Alterar",
            "comum.excluir": "Excluir",
            "comum.fechar": "Fechar",
            "comum.cancelar": "Cancelar",
            "comum.confirmacao": "Confirmação",
            "comum.erro_prefixo": "Erro: ",

            # Tela de Clientes
            "cliente.janela_titulo": "CRUD de Clientes",
            "cliente.titulo": "Cadastro de Clientes",
            "cliente.dados_frame": "Dados do cliente",
            "cliente.data_nascimento": "Nascimento (DD/MM/AAAA):",
            "cliente.limite_credito": "Limite de crédito:",
            "cliente.estado": "Estado:",
            "cliente.cidade": "Cidade:",
            "cliente.coluna_nascimento": "Nascimento",
            "cliente.coluna_idade": "Idade",
            "cliente.coluna_limite": "Limite de crédito",
            "cliente.coluna_uf": "UF",
            "cliente.confirmar_exclusao": "Deseja realmente excluir este cliente?",
            "cliente.cadastrado_sucesso": "Cliente cadastrado com sucesso!",
            "cliente.atualizado_sucesso": "Cliente atualizado com sucesso!",
            "cliente.excluido_sucesso": "Cliente excluído com sucesso!",
            "cliente.selecione_da_lista": "Selecione um cliente na lista.",
            "cliente.nao_encontrado": "Cliente não encontrado.",
            "cliente.erro_ao_excluir": "Problemas ao excluir cliente",
            "cliente.erro_data_invalida": "Data de nascimento inválida. Use o formato DD/MM/AAAA.",
            "cliente.erro_limite_invalido": "Informe um valor numérico válido para o limite de crédito.",
            "cliente.erro_selecionar_cidade": "Selecione uma cidade.",

            # Tela de Estados
            "estado.janela_titulo": "CRUD de Estados",
            "estado.titulo": "Cadastro de Estados",
            "estado.dados_frame": "Dados do estado",
            "estado.sigla": "Sigla",
            "estado.confirmar_exclusao": "Deseja realmente excluir este estado?",
            "estado.cadastrado_sucesso": "Estado cadastrado com sucesso!",
            "estado.atualizado_sucesso": "Estado atualizado com sucesso!",
            "estado.excluido_sucesso": "Estado excluído com sucesso!",
            "estado.nao_encontrado": "Estado não encontrado.",
            "estado.selecione_da_lista": "Selecione um estado na lista.",
            "estado.erro_ao_excluir": "Problemas ao excluir estado",
            "estado.erro_sigla_tamanho": "A sigla deve possuir exatamente 2 caracteres.",

            # Menu principal
            "menu.cadastros_basicos": "Cadastros básicos",
            "menu.estados": "Estados",
            "menu.cidades": "Cidades",
            "menu.acessos": "Acessos",
            "menu.usuarios": "Usuários",
            "menu.perfis": "Perfis",
            "menu.gestao_estoque": "Gestão de estoque",
            "menu.clientes": "Clientes",
            "menu.fornecedores": "Fornecedores",
            "menu.produtos": "Produtos",
            "menu.categorias": "Categorias",
            "menu.idioma": "Idioma",
            "menu.sair": "Sair",

            # Tela de Cidades
            "janela.cidade": "CRUD de cidades",
            "cadastro.cidades": "Cadastro de cidades",
            "dados.cidades": "Dados da cidade",
            "cidade.estado": "Estado",
            "cidade.confirmacao": "Confirmação",
            "cidade.excluir": "Deseja realmente excluir esta cidade?",
            "cidade.selecionar_estado": "Selecione um estado",
            "cidade.sucesso": "Mini ERP",
            "cidade.cadastro_sucesso": "Cidade cadastrada com sucesso!",
            "cidade.atualizada_sucesso": "Cidade atualizada com sucesso!",
            "cidade.selecionar": "Selecione uma cidade na lista.",
            "cidade.excluida_sucesso": "Cidade excluída com sucesso!",
            "cidade.nao_encotrada": "Cidade não encontrada",
            "cidade.problemas": "Problemas ao excluir cidade",

            # Tela de Categorias
            "categoria.janela": "CRUD de Categorias",
            "categoria.cadastro": "Cadastro de Categorias",
            "categoria.dados": "Dados da categoria",
            "categoria.confirmacao": "Deseja realmente excluir esta categoria?",
            "categoria.cadastrada_sucesso": "Categoria cadastrada com sucesso!",
            "categoria.selecionar": "Selecione uma categoria na lista",
            "categoria.atualizada_sucesso": "Categoria atualizada com sucesso!",
            "categoria.excluida_sucesso": "Categoria excluída com sucesso!",
            "categoria.nao_encontrada": "Categoria não encontrada",
            "categoria.problemas": "Problemas ao excluir categoria",

            # Fornecedor categoria
            "fcategoria.janela": "Categorias de ",
            "fcategoria.instrucao": "Clique para marcar/desmarcar as categorias deste fornecedor:",

            # Tela de Fornecedores
            "fornecedor.janela": "CRUD de Fornecedores",
            "fornecedor.titulo": "Cadastro de Fornecedores",
            "fornecedor.dados": "Dados do fornecedor",
            "fornecedor.razao_social": "Razão social:",
            "fornecedor.nome_fantasia": "Nome fantasia:",
            "fornecedor.cnpj": "CNPJ:",
            "fornecedor.sla": "SLA de atendimento:",
            "fornecedor.categorias": "Categorias",
            "fornecedor.confirmar_exclusao": "Deseja realmente excluir este fornecedor?",
            "fornecedor.sucesso": "Mini ERP",
            "fornecedor.razao_social_coluna": "Razão Social",
            "fornecedor.cnpj_coluna": "CNPJ",

            # Controller de Fornecedores
            "fornecedor.cadastrado_sucesso": "Fornecedor cadastrado com sucesso!",
            "fornecedor.entrada_invalida": "Erro: Entrada inválida. Tente novamente.",
            "fornecedor.selecionar": "Selecione um fornecedor na lista.",
            "fornecedor.atualizado_sucesso": "Fornecedor atualizado com sucesso!",
            "fornecedor.excluido_sucesso": "Fornecedor excluído com sucesso!",
            "fornecedor.nao_encontrado": "Fornecedor não encontrado.",
            "fornecedor.problemas": "Problemas ao excluir fornecedor",
            "fornecedor.cadastrar_categorias": "Cadastre categorias antes de associá-las a um fornecedor.",
            "fornecedor.categorias_atualizadas_sucesso": "Categorias do fornecedor atualizadas com sucesso!",
            "fornecedor.categorias_erro": "Não foi possível salvar as categorias do fornecedor.",

            # Perfil
            "perfil.janela": "CRUD de Perfis",
            "perfil.titulo": "Cadastro de Perfis",
            "perfil.dados": "Dados do perfil",
            "perfil.descricao": "Descrição",
            "perfil.fornecedores": "Fornecedores",
            "perfil.confirmar_exclusao": "Deseja realmente excluir este perfil?",
            "perfil.cadastrado_sucesso": "Perfil cadastrado com sucesso!",
            "perfil.selecionar": "Selecione um perfil na lista.",
            "perfil.atualizado_sucesso": "Perfil atualizado com sucesso!",
            "perfil.excluido_sucesso": "Perfil excluído com sucesso!",
            "perfil.nao_encontrado": "Perfil não encontrado.",
            "perfil.problemas": "Problemas ao excluir perfil",
            "perfil.cadastrar_fornecedores": "Cadastre fornecedores antes de associá-los a um perfil.",
            "perfil.id_coluna": "ID",
            "perfil.nome_coluna": "Nome",
            "perfil.descricao_coluna": "Descrição",

            # Perfil fornecedor
            "perfil_fornecedor.janela": "Fornecedores do perfil",
            "perfil_fornecedor.titulo": "Fornecedores do perfil",
            "perfil_fornecedor.instrucao": "Clique para marcar/desmarcar os fornecedores deste perfil:",
            "perfil_fornecedor.sucesso": "Mini ERP",
            "perfil_fornecedor.atualizados_sucesso": "Fornecedores do perfil atualizados com sucesso!",
            "perfil_fornecedor.erro": "Não foi possível salvar os fornecedores do perfil.",

              # Tela de Produtos
            "produto.janela_titulo": "CRUD de Produtos",
            "produto.titulo": "Cadastro de Produtos",
            "produto.dados_frame": "Dados do produto",
            "produto.fornecedor": "Fornecedor:",
            "produto.estoque": "Estoque:",
            "produto.preco": "Preço:",
            "produto.coluna_estoque": "Estoque",
            "produto.coluna_preco": "Preço",
            "produto.coluna_valor_estoque": "Valor em estoque",
            "produto.coluna_fornecedor": "Fornecedor",
            "produto.confirmar_exclusao": "Deseja realmente excluir este produto?",
            "produto.cadastrado_sucesso": "Produto cadastrado com sucesso!",
            "produto.atualizado_sucesso": "Produto atualizado com sucesso!",
            "produto.excluido_sucesso": "Produto excluído com sucesso!",
            "produto.selecionar": "Selecione um produto na lista.",
            "produto.nao_encontrado": "Produto não encontrado.",
            "produto.problemas": "Problemas ao excluir produto",
            "produto.selecione_fornecedor": "Selecione um fornecedor.",

              # Tela de Usuários
            "usuario.janela_titulo": "CRUD de Usuários",
            "usuario.titulo": "Cadastro de Usuários",
            "usuario.dados_frame": "Dados do usuário",
            "usuario.email": "Email:",
            "usuario.data_nascimento": "Nascimento (DD/MM/AAAA):",
            "usuario.estado": "Estado:",
            "usuario.cidade": "Cidade:",
            "usuario.perfil": "Perfil:",
            "usuario.coluna_email": "Email",
            "usuario.coluna_nascimento": "Nascimento",
            "usuario.coluna_idade": "Idade",
            "usuario.coluna_cidade": "Cidade",
            "usuario.coluna_uf": "UF",
            "usuario.coluna_perfil": "Perfil",
            "usuario.confirmar_exclusao": "Deseja realmente excluir este usuário?",
            "usuario.cadastrado_sucesso": "Usuário cadastrado com sucesso!",
            "usuario.atualizado_sucesso": "Usuário atualizado com sucesso!",
            "usuario.excluido_sucesso": "Usuário excluído com sucesso!",
            "usuario.selecionar": "Selecione um usuário na lista.",
            "usuario.nao_encontrado": "Usuário não encontrado.",
            "usuario.problemas": "Problemas ao excluir usuário",
            "usuario.erro_data_invalida": "Data de nascimento inválida. Use o formato DD/MM/AAAA.",
            "usuario.erro_selecionar_cidade": "Selecione uma cidade.",
            "usuario.erro_selecionar_perfil": "Selecione um perfil.",


        },

        "en": {
            # Common to several screens
            "comum.id": "ID",
            "comum.nome": "Name",
            "comum.novo": "New",
            "comum.salvar": "Save",
            "comum.alterar": "Edit",
            "comum.excluir": "Delete",
            "comum.fechar": "Close",
            "comum.cancelar": "Cancel",
            "comum.confirmacao": "Confirmation",
            "comum.erro_prefixo": "Error: ",

            # Customers screen
            "cliente.janela_titulo": "Customer Management",
            "cliente.titulo": "Customer Registration",
            "cliente.dados_frame": "Customer data",
            "cliente.data_nascimento": "Birthdate (DD/MM/YYYY):",
            "cliente.limite_credito": "Credit limit:",
            "cliente.estado": "State:",
            "cliente.cidade": "City:",
            "cliente.coluna_nascimento": "Birthdate",
            "cliente.coluna_idade": "Age",
            "cliente.coluna_limite": "Credit Limit",
            "cliente.coluna_uf": "State",
            "cliente.confirmar_exclusao": "Do you really want to delete this customer?",
            "cliente.cadastrado_sucesso": "Customer registered successfully!",
            "cliente.atualizado_sucesso": "Customer updated successfully!",
            "cliente.excluido_sucesso": "Customer deleted successfully!",
            "cliente.selecione_da_lista": "Select a customer from the list.",
            "cliente.nao_encontrado": "Customer not found.",
            "cliente.erro_ao_excluir": "Problem deleting customer",
            "cliente.erro_data_invalida": "Invalid birthdate. Use the format DD/MM/YYYY.",
            "cliente.erro_limite_invalido": "Please enter a valid numeric value for the credit limit.",
            "cliente.erro_selecionar_cidade": "Please select a city.",

            # States screen
            "estado.janela_titulo": "State Management",
            "estado.titulo": "State Registration",
            "estado.dados_frame": "State data",
            "estado.sigla": "Abbreviation",
            "estado.confirmar_exclusao": "Do you really want to delete this state?",
            "estado.cadastrado_sucesso": "State registered successfully!",
            "estado.atualizado_sucesso": "State updated successfully!",
            "estado.excluido_sucesso": "State deleted successfully!",
            "estado.nao_encontrado": "State not found.",
            "estado.selecione_da_lista": "Select a state from the list.",
            "estado.erro_ao_excluir": "Problem deleting state",
            "estado.erro_sigla_tamanho": "The abbreviation must have exactly 2 characters.",

            # Main menu
            "menu.cadastros_basicos": "Basic registrations",
            "menu.estados": "States",
            "menu.cidades": "Cities",
            "menu.acessos": "Access",
            "menu.usuarios": "Users",
            "menu.perfis": "Roles",
            "menu.gestao_estoque": "Inventory management",
            "menu.clientes": "Customers",
            "menu.fornecedores": "Suppliers",
            "menu.produtos": "Products",
            "menu.categorias": "Categories",
            "menu.idioma": "Language",
            "menu.sair": "Exit",

            # Cities screen
            "janela.cidade": "City CRUD",
            "cadastro.cidades": "City registration",
            "dados.cidades": "City data",
            "cidade.estado": "State",
            "cidade.confirmacao": "Confirmation",
            "cidade.excluir": "Do you really want to delete this city?",
            "cidade.selecionar_estado": "Select a state",
            "cidade.sucesso": "Mini ERP",
            "cidade.cadastro_sucesso": "City successfully registered!",
            "cidade.atualizada_sucesso": "City successfully updated!",
            "cidade.selecionar": "Select a city from the list.",
            "cidade.excluida_sucesso": "City successfully deleted!",
            "cidade.nao_encotrada": "City not found",
            "cidade.problemas": "Problems deleting city",

            # Categories screen
            "categoria.janela": "Category CRUD",
            "categoria.cadastro": "Category registration",
            "categoria.dados": "Category data",
            "categoria.confirmacao": "Do you really want to delete this category?",
            "categoria.cadastrada_sucesso": "Category successfully registered!",
            "categoria.selecionar": "Select a category from the list",
            "categoria.atualizada_sucesso": "Category successfully updated!",
            "categoria.excluida_sucesso": "Category successfully deleted!",
            "categoria.nao_encontrada": "Category not found",
            "categoria.problemas": "Problems deleting category",

            # Supplier category
            "fcategoria.janela": "Categories of ",
            "fcategoria.instrucao": "Click to mark/unmark this supplier's categories:",

            # Suppliers screen
            "fornecedor.janela": "Supplier CRUD",
            "fornecedor.titulo": "Supplier Registration",
            "fornecedor.dados": "Supplier data",
            "fornecedor.razao_social": "Company name:",
            "fornecedor.nome_fantasia": "Trade name:",
            "fornecedor.cnpj": "CNPJ:",
            "fornecedor.sla": "Service SLA:",
            "fornecedor.categorias": "Categories",
            "fornecedor.confirmar_exclusao": "Do you really want to delete this supplier?",
            "fornecedor.sucesso": "Mini ERP",
            "fornecedor.razao_social_coluna": "Company Name",
            "fornecedor.cnpj_coluna": "CNPJ",

            # Supplier Controller
            "fornecedor.cadastrado_sucesso": "Supplier registered successfully!",
            "fornecedor.entrada_invalida": "Error: Invalid input. Please try again.",
            "fornecedor.selecionar": "Select a supplier from the list.",
            "fornecedor.atualizado_sucesso": "Supplier updated successfully!",
            "fornecedor.excluido_sucesso": "Supplier deleted successfully!",
            "fornecedor.nao_encontrado": "Supplier not found.",
            "fornecedor.problemas": "Problems deleting supplier",
            "fornecedor.cadastrar_categorias": "Register categories before associating them with a supplier.",
            "fornecedor.categorias_atualizadas_sucesso": "Supplier categories updated successfully!",
            "fornecedor.categorias_erro": "Could not save the supplier categories.",

            # Profile
            "perfil.janela": "Profile CRUD",
            "perfil.titulo": "Profile Registration",
            "perfil.dados": "Profile data",
            "perfil.descricao": "Description",
            "perfil.fornecedores": "Suppliers",
            "perfil.confirmar_exclusao": "Do you really want to delete this profile?",
            "perfil.cadastrado_sucesso": "Profile registered successfully!",
            "perfil.selecionar": "Select a profile from the list.",
            "perfil.atualizado_sucesso": "Profile updated successfully!",
            "perfil.excluido_sucesso": "Profile deleted successfully!",
            "perfil.nao_encontrado": "Profile not found.",
            "perfil.problemas": "Problems deleting profile",
            "perfil.cadastrar_fornecedores": "Register suppliers before associating them with a profile.",
            "perfil.id_coluna": "ID",
            "perfil.nome_coluna": "Name",
            "perfil.descricao_coluna": "Description",

            # Profile supplier
            "perfil_fornecedor.janela": "Suppliers of profile",
            "perfil_fornecedor.titulo": "Suppliers of profile",
            "perfil_fornecedor.instrucao": "Click to mark/unmark the suppliers of this profile:",
            "perfil_fornecedor.sucesso": "Mini ERP",
            "perfil_fornecedor.atualizados_sucesso": "Profile suppliers updated successfully!",
            "perfil_fornecedor.erro": "Could not save the profile suppliers.",

               # Products screen
            "produto.janela_titulo": "Product Management",
            "produto.titulo": "Product Registration",
            "produto.dados_frame": "Product data",
            "produto.fornecedor": "Supplier:",
            "produto.estoque": "Stock:",
            "produto.preco": "Price:",
            "produto.coluna_estoque": "Stock",
            "produto.coluna_preco": "Price",
            "produto.coluna_valor_estoque": "Stock value",
            "produto.coluna_fornecedor": "Supplier",
            "produto.confirmar_exclusao": "Do you really want to delete this product?",
            "produto.cadastrado_sucesso": "Product registered successfully!",
            "produto.atualizado_sucesso": "Product updated successfully!",
            "produto.excluido_sucesso": "Product deleted successfully!",
            "produto.selecionar": "Select a product from the list.",
            "produto.nao_encontrado": "Product not found.",
            "produto.problemas": "Problem deleting product",
            "produto.selecione_fornecedor": "Please select a supplier.",

               # Users screen
            "usuario.janela_titulo": "User Management",
            "usuario.titulo": "User Registration",
            "usuario.dados_frame": "User data",
            "usuario.email": "Email:",
            "usuario.data_nascimento": "Birthdate (DD/MM/YYYY):",
            "usuario.estado": "State:",
            "usuario.cidade": "City:",
            "usuario.perfil": "Role:",
            "usuario.coluna_email": "Email",
            "usuario.coluna_nascimento": "Birthdate",
            "usuario.coluna_idade": "Age",
            "usuario.coluna_cidade": "City",
            "usuario.coluna_uf": "State",
            "usuario.coluna_perfil": "Role",
            "usuario.confirmar_exclusao": "Do you really want to delete this user?",
            "usuario.cadastrado_sucesso": "User registered successfully!",
            "usuario.atualizado_sucesso": "User updated successfully!",
            "usuario.excluido_sucesso": "User deleted successfully!",
            "usuario.selecionar": "Select a user from the list.",
            "usuario.nao_encontrado": "User not found.",
            "usuario.problemas": "Problem deleting user",
            "usuario.erro_data_invalida": "Invalid birthdate. Use the format DD/MM/YYYY.",
            "usuario.erro_selecionar_cidade": "Please select a city.",
            "usuario.erro_selecionar_perfil": "Please select a role.",

        },
          "es": {
            # Comunes a varias pantallas
            "comum.id": "ID",
            "comum.nome": "Nombre",
            "comum.novo": "Nuevo",
            "comum.salvar": "Guardar",
            "comum.alterar": "Editar",
            "comum.excluir": "Eliminar",
            "comum.fechar": "Cerrar",
            "comum.cancelar": "Cancelar",
            "comum.confirmacao": "Confirmación",
            "comum.erro_prefixo": "Error: ",
 
            # Pantalla de Clientes
            "cliente.janela_titulo": "Gestión de Clientes",
            "cliente.titulo": "Registro de Clientes",
            "cliente.dados_frame": "Datos del cliente",
            "cliente.data_nascimento": "Fecha de nacimiento (DD/MM/AAAA):",
            "cliente.limite_credito": "Límite de crédito:",
            "cliente.estado": "Estado:",
            "cliente.cidade": "Ciudad:",
            "cliente.coluna_nascimento": "Nacimiento",
            "cliente.coluna_idade": "Edad",
            "cliente.coluna_limite": "Límite de crédito",
            "cliente.coluna_uf": "Estado",
            "cliente.confirmar_exclusao": "¿Desea realmente eliminar este cliente?",
            "cliente.cadastrado_sucesso": "¡Cliente registrado con éxito!",
            "cliente.atualizado_sucesso": "¡Cliente actualizado con éxito!",
            "cliente.excluido_sucesso": "¡Cliente eliminado con éxito!",
            "cliente.selecione_da_lista": "Seleccione un cliente de la lista.",
            "cliente.nao_encontrado": "Cliente no encontrado.",
            "cliente.erro_ao_excluir": "Problemas al eliminar el cliente",
            "cliente.erro_data_invalida": "Fecha de nacimiento inválida. Use el formato DD/MM/AAAA.",
            "cliente.erro_limite_invalido": "Ingrese un valor numérico válido para el límite de crédito.",
            "cliente.erro_selecionar_cidade": "Seleccione una ciudad.",
 
            # Pantalla de Estados
            "estado.janela_titulo": "Gestión de Estados",
            "estado.titulo": "Registro de Estados",
            "estado.dados_frame": "Datos del estado",
            "estado.sigla": "Sigla",
            "estado.confirmar_exclusao": "¿Desea realmente eliminar este estado?",
            "estado.cadastrado_sucesso": "¡Estado registrado con éxito!",
            "estado.atualizado_sucesso": "¡Estado actualizado con éxito!",
            "estado.excluido_sucesso": "¡Estado eliminado con éxito!",
            "estado.nao_encontrado": "Estado no encontrado.",
            "estado.selecione_da_lista": "Seleccione un estado de la lista.",
            "estado.erro_ao_excluir": "Problemas al eliminar el estado",
            "estado.erro_sigla_tamanho": "La sigla debe tener exactamente 2 caracteres.",
 
            # Menú principal
            "menu.cadastros_basicos": "Registros básicos",
            "menu.estados": "Estados",
            "menu.cidades": "Ciudades",
            "menu.acessos": "Accesos",
            "menu.usuarios": "Usuarios",
            "menu.perfis": "Perfiles",
            "menu.gestao_estoque": "Gestión de inventario",
            "menu.clientes": "Clientes",
            "menu.fornecedores": "Proveedores",
            "menu.produtos": "Productos",
            "menu.categorias": "Categorías",
            "menu.idioma": "Idioma",
            "menu.sair": "Salir",
 
            # Pantalla de Ciudades
            "janela.cidade": "Gestión de ciudades",
            "cadastro.cidades": "Registro de ciudades",
            "dados.cidades": "Datos de la ciudad",
            "cidade.estado": "Estado",
            "cidade.confirmacao": "Confirmación",
            "cidade.excluir": "¿Desea realmente eliminar esta ciudad?",
            "cidade.selecionar_estado": "Seleccione un estado",
            "cidade.sucesso": "Mini ERP",
            "cidade.cadastro_sucesso": "¡Ciudad registrada con éxito!",
            "cidade.atualizada_sucesso": "¡Ciudad actualizada con éxito!",
            "cidade.selecionar": "Seleccione una ciudad de la lista.",
            "cidade.excluida_sucesso": "¡Ciudad eliminada con éxito!",
            "cidade.nao_encotrada": "Ciudad no encontrada",
            "cidade.problemas": "Problemas al eliminar la ciudad",
 
            # Pantalla de Categorías
            "categoria.janela": "Gestión de Categorías",
            "categoria.cadastro": "Registro de Categorías",
            "categoria.dados": "Datos de la categoría",
            "categoria.confirmacao": "¿Desea realmente eliminar esta categoría?",
            "categoria.cadastrada_sucesso": "¡Categoría registrada con éxito!",
            "categoria.selecionar": "Seleccione una categoría de la lista",
            "categoria.atualizada_sucesso": "¡Categoría actualizada con éxito!",
            "categoria.excluida_sucesso": "¡Categoría eliminada con éxito!",
            "categoria.nao_encontrada": "Categoría no encontrada",
            "categoria.problemas": "Problemas al eliminar la categoría",
 
            # Categoría de proveedor
            "fcategoria.janela": "Categorías de ",
            "fcategoria.instrucao": "Haga clic para marcar/desmarcar las categorías de este proveedor:",
 
            # Pantalla de Proveedores
            "fornecedor.janela": "Gestión de Proveedores",
            "fornecedor.titulo": "Registro de Proveedores",
            "fornecedor.dados": "Datos del proveedor",
            "fornecedor.razao_social": "Razón social:",
            "fornecedor.nome_fantasia": "Nombre comercial:",
            "fornecedor.cnpj": "CNPJ:",
            "fornecedor.sla": "SLA de atención:",
            "fornecedor.categorias": "Categorías",
            "fornecedor.confirmar_exclusao": "¿Desea realmente eliminar este proveedor?",
            "fornecedor.sucesso": "Mini ERP",
            "fornecedor.razao_social_coluna": "Razón Social",
            "fornecedor.cnpj_coluna": "CNPJ",
 
            # Controlador de Proveedores
            "fornecedor.cadastrado_sucesso": "¡Proveedor registrado con éxito!",
            "fornecedor.entrada_invalida": "Error: Entrada inválida. Intente nuevamente.",
            "fornecedor.selecionar": "Seleccione un proveedor de la lista.",
            "fornecedor.atualizado_sucesso": "¡Proveedor actualizado con éxito!",
            "fornecedor.excluido_sucesso": "¡Proveedor eliminado con éxito!",
            "fornecedor.nao_encontrado": "Proveedor no encontrado.",
            "fornecedor.problemas": "Problemas al eliminar el proveedor",
            "fornecedor.cadastrar_categorias": "Registre categorías antes de asociarlas a un proveedor.",
            "fornecedor.categorias_atualizadas_sucesso": "¡Categorías del proveedor actualizadas con éxito!",
            "fornecedor.categorias_erro": "No fue posible guardar las categorías del proveedor.",
 
            # Perfil
            "perfil.janela": "Gestión de Perfiles",
            "perfil.titulo": "Registro de Perfiles",
            "perfil.dados": "Datos del perfil",
            "perfil.descricao": "Descripción",
            "perfil.fornecedores": "Proveedores",
            "perfil.confirmar_exclusao": "¿Desea realmente eliminar este perfil?",
            "perfil.cadastrado_sucesso": "¡Perfil registrado con éxito!",
            "perfil.selecionar": "Seleccione un perfil de la lista.",
            "perfil.atualizado_sucesso": "¡Perfil actualizado con éxito!",
            "perfil.excluido_sucesso": "¡Perfil eliminado con éxito!",
            "perfil.nao_encontrado": "Perfil no encontrado.",
            "perfil.problemas": "Problemas al eliminar el perfil",
            "perfil.cadastrar_fornecedores": "Registre proveedores antes de asociarlos a un perfil.",
            "perfil.id_coluna": "ID",
            "perfil.nome_coluna": "Nombre",
            "perfil.descricao_coluna": "Descripción",
 
            # Perfil proveedor
            "perfil_fornecedor.janela": "Proveedores del perfil",
            "perfil_fornecedor.titulo": "Proveedores del perfil",
            "perfil_fornecedor.instrucao": "Haga clic para marcar/desmarcar los proveedores de este perfil:",
            "perfil_fornecedor.sucesso": "Mini ERP",
            "perfil_fornecedor.atualizados_sucesso": "¡Proveedores del perfil actualizados con éxito!",
            "perfil_fornecedor.erro": "No fue posible guardar los proveedores del perfil.",
 
            # Pantalla de Productos
            "produto.janela_titulo": "Gestión de Productos",
            "produto.titulo": "Registro de Productos",
            "produto.dados_frame": "Datos del producto",
            "produto.fornecedor": "Proveedor:",
            "produto.estoque": "Existencias:",
            "produto.preco": "Precio:",
            "produto.coluna_estoque": "Existencias",
            "produto.coluna_preco": "Precio",
            "produto.coluna_valor_estoque": "Valor en existencias",
            "produto.coluna_fornecedor": "Proveedor",
            "produto.confirmar_exclusao": "¿Desea realmente eliminar este producto?",
            "produto.cadastrado_sucesso": "¡Producto registrado con éxito!",
            "produto.atualizado_sucesso": "¡Producto actualizado con éxito!",
            "produto.excluido_sucesso": "¡Producto eliminado con éxito!",
            "produto.selecionar": "Seleccione un producto de la lista.",
            "produto.nao_encontrado": "Producto no encontrado.",
            "produto.problemas": "Problemas al eliminar el producto",
            "produto.selecione_fornecedor": "Seleccione un proveedor.",
 
            # Pantalla de Usuarios
            "usuario.janela_titulo": "Gestión de Usuarios",
            "usuario.titulo": "Registro de Usuarios",
            "usuario.dados_frame": "Datos del usuario",
            "usuario.email": "Correo electrónico:",
            "usuario.data_nascimento": "Fecha de nacimiento (DD/MM/AAAA):",
            "usuario.estado": "Estado:",
            "usuario.cidade": "Ciudad:",
            "usuario.perfil": "Perfil:",
            "usuario.coluna_email": "Correo electrónico",
            "usuario.coluna_nascimento": "Nacimiento",
            "usuario.coluna_idade": "Edad",
            "usuario.coluna_cidade": "Ciudad",
            "usuario.coluna_uf": "Estado",
            "usuario.coluna_perfil": "Perfil",
            "usuario.confirmar_exclusao": "¿Desea realmente eliminar este usuario?",
            "usuario.cadastrado_sucesso": "¡Usuario registrado con éxito!",
            "usuario.atualizado_sucesso": "¡Usuario actualizado con éxito!",
            "usuario.excluido_sucesso": "¡Usuario eliminado con éxito!",
            "usuario.selecionar": "Seleccione un usuario de la lista.",
            "usuario.nao_encontrado": "Usuario no encontrado.",
            "usuario.problemas": "Problemas al eliminar el usuario",
            "usuario.erro_data_invalida": "Fecha de nacimiento inválida. Use el formato DD/MM/AAAA.",
            "usuario.erro_selecionar_cidade": "Seleccione una ciudad.",
            "usuario.erro_selecionar_perfil": "Seleccione un perfil.",
        },

                "ru": {
            # Общие для нескольких экранов
            "comum.id": "ID",
            "comum.nome": "Имя",
            "comum.novo": "Новый",
            "comum.salvar": "Сохранить",
            "comum.alterar": "Изменить",
            "comum.excluir": "Удалить",
            "comum.fechar": "Закрыть",
            "comum.cancelar": "Отмена",
            "comum.confirmacao": "Подтверждение",
            "comum.erro_prefixo": "Ошибка: ",

            # Экран Клиентов
            "cliente.janela_titulo": "Управление клиентами",
            "cliente.titulo": "Регистрация клиента",
            "cliente.dados_frame": "Данные клиента",
            "cliente.data_nascimento": "Дата рождения (ДД/ММ/ГГГГ):",
            "cliente.limite_credito": "Кредитный лимит:",
            "cliente.estado": "Штат:",
            "cliente.cidade": "Город:",
            "cliente.coluna_nascimento": "Дата рождения",
            "cliente.coluna_idade": "Возраст",
            "cliente.coluna_limite": "Кредитный лимит",
            "cliente.coluna_uf": "Штат",
            "cliente.confirmar_exclusao": "Вы действительно хотите удалить этого клиента?",
            "cliente.cadastrado_sucesso": "Клиент успешно зарегистрирован!",
            "cliente.atualizado_sucesso": "Клиент успешно обновлён!",
            "cliente.excluido_sucesso": "Клиент успешно удалён!",
            "cliente.selecione_da_lista": "Выберите клиента из списка.",
            "cliente.nao_encontrado": "Клиент не найден.",
            "cliente.erro_ao_excluir": "Ошибка при удалении клиента",
            "cliente.erro_data_invalida": "Неверная дата рождения. Используйте формат ДД/ММ/ГГГГ.",
            "cliente.erro_limite_invalido": "Введите корректное числовое значение кредитного лимита.",
            "cliente.erro_selecionar_cidade": "Выберите город.",

            # Экран Штатов
            "estado.janela_titulo": "Управление штатами",
            "estado.titulo": "Регистрация штата",
            "estado.dados_frame": "Данные штата",
            "estado.sigla": "Аббревиатура",
            "estado.confirmar_exclusao": "Вы действительно хотите удалить этот штат?",
            "estado.cadastrado_sucesso": "Штат успешно зарегистрирован!",
            "estado.atualizado_sucesso": "Штат успешно обновлён!",
            "estado.excluido_sucesso": "Штат успешно удалён!",
            "estado.nao_encontrado": "Штат не найден.",
            "estado.selecione_da_lista": "Выберите штат из списка.",
            "estado.erro_ao_excluir": "Ошибка при удалении штата",
            "estado.erro_sigla_tamanho": "Аббревиатура должна содержать ровно 2 символа.",

            # Главное меню
            "menu.cadastros_basicos": "Базовые справочники",
            "menu.estados": "Штаты",
            "menu.cidades": "Города",
            "menu.acessos": "Доступ",
            "menu.usuarios": "Пользователи",
            "menu.perfis": "Профили",
            "menu.gestao_estoque": "Управление запасами",
            "menu.clientes": "Клиенты",
            "menu.fornecedores": "Поставщики",
            "menu.produtos": "Товары",
            "menu.categorias": "Категории",
            "menu.idioma": "Язык",
            "menu.sair": "Выход",

            # Экран Городов
            "janela.cidade": "Управление городами",
            "cadastro.cidades": "Регистрация города",
            "dados.cidades": "Данные города",
            "cidade.estado": "Штат",
            "cidade.confirmacao": "Подтверждение",
            "cidade.excluir": "Вы действительно хотите удалить этот город?",
            "cidade.selecionar_estado": "Выберите штат",
            "cidade.sucesso": "Mini ERP",
            "cidade.cadastro_sucesso": "Город успешно зарегистрирован!",
            "cidade.atualizada_sucesso": "Город успешно обновлён!",
            "cidade.selecionar": "Выберите город из списка.",
            "cidade.excluida_sucesso": "Город успешно удалён!",
            "cidade.nao_encotrada": "Город не найден",
            "cidade.problemas": "Ошибка при удалении города",

            # Экран Категорий
            "categoria.janela": "Управление категориями",
            "categoria.cadastro": "Регистрация категории",
            "categoria.dados": "Данные категории",
            "categoria.confirmacao": "Вы действительно хотите удалить эту категорию?",
            "categoria.cadastrada_sucesso": "Категория успешно зарегистрирована!",
            "categoria.selecionar": "Выберите категорию из списка",
            "categoria.atualizada_sucesso": "Категория успешно обновлена!",
            "categoria.excluida_sucesso": "Категория успешно удалена!",
            "categoria.nao_encontrada": "Категория не найдена",
            "categoria.problemas": "Ошибка при удалении категории",

            # Категория поставщика
            "fcategoria.janela": "Категории ",
            "fcategoria.instrucao": "Нажмите, чтобы отметить/снять категории этого поставщика:",

            # Экран Поставщиков
            "fornecedor.janela": "Управление поставщиками",
            "fornecedor.titulo": "Регистрация поставщика",
            "fornecedor.dados": "Данные поставщика",
            "fornecedor.razao_social": "Юридическое название:",
            "fornecedor.nome_fantasia": "Торговое название:",
            "fornecedor.cnpj": "CNPJ:",
            "fornecedor.sla": "SLA обслуживания:",
            "fornecedor.categorias": "Категории",
            "fornecedor.confirmar_exclusao": "Вы действительно хотите удалить этого поставщика?",
            "fornecedor.sucesso": "Mini ERP",
            "fornecedor.razao_social_coluna": "Юридическое название",
            "fornecedor.cnpj_coluna": "CNPJ",

            # Контроллер Поставщиков
            "fornecedor.cadastrado_sucesso": "Поставщик успешно зарегистрирован!",
            "fornecedor.entrada_invalida": "Ошибка: неверные данные. Попробуйте снова.",
            "fornecedor.selecionar": "Выберите поставщика из списка.",
            "fornecedor.atualizado_sucesso": "Поставщик успешно обновлён!",
            "fornecedor.excluido_sucesso": "Поставщик успешно удалён!",
            "fornecedor.nao_encontrado": "Поставщик не найден.",
            "fornecedor.problemas": "Ошибка при удалении поставщика",
            "fornecedor.cadastrar_categorias": "Зарегистрируйте категории перед их привязкой к поставщику.",
            "fornecedor.categorias_atualizadas_sucesso": "Категории поставщика успешно обновлены!",
            "fornecedor.categorias_erro": "Не удалось сохранить категории поставщика.",

            # Профиль
            "perfil.janela": "Управление профилями",
            "perfil.titulo": "Регистрация профиля",
            "perfil.dados": "Данные профиля",
            "perfil.descricao": "Описание",
            "perfil.fornecedores": "Поставщики",
            "perfil.confirmar_exclusao": "Вы действительно хотите удалить этот профиль?",
            "perfil.cadastrado_sucesso": "Профиль успешно зарегистрирован!",
            "perfil.selecionar": "Выберите профиль из списка.",
            "perfil.atualizado_sucesso": "Профиль успешно обновлён!",
            "perfil.excluido_sucesso": "Профиль успешно удалён!",
            "perfil.nao_encontrado": "Профиль не найден.",
            "perfil.problemas": "Ошибка при удалении профиля",
            "perfil.cadastrar_fornecedores": "Зарегистрируйте поставщиков перед их привязкой к профилю.",
            "perfil.id_coluna": "ID",
            "perfil.nome_coluna": "Имя",
            "perfil.descricao_coluna": "Описание",

            # Профиль поставщика
            "perfil_fornecedor.janela": "Поставщики профиля",
            "perfil_fornecedor.titulo": "Поставщики профиля",
            "perfil_fornecedor.instrucao": "Нажмите, чтобы отметить/снять поставщиков этого профиля:",
            "perfil_fornecedor.sucesso": "Mini ERP",
            "perfil_fornecedor.atualizados_sucesso": "Поставщики профиля успешно обновлены!",
            "perfil_fornecedor.erro": "Не удалось сохранить поставщиков профиля.",

            # Экран Товаров
            "produto.janela_titulo": "Управление товарами",
            "produto.titulo": "Регистрация товара",
            "produto.dados_frame": "Данные товара",
            "produto.fornecedor": "Поставщик:",
            "produto.estoque": "Запас:",
            "produto.preco": "Цена:",
            "produto.coluna_estoque": "Запас",
            "produto.coluna_preco": "Цена",
            "produto.coluna_valor_estoque": "Стоимость запаса",
            "produto.coluna_fornecedor": "Поставщик",
            "produto.confirmar_exclusao": "Вы действительно хотите удалить этот товар?",
            "produto.cadastrado_sucesso": "Товар успешно зарегистрирован!",
            "produto.atualizado_sucesso": "Товар успешно обновлён!",
            "produto.excluido_sucesso": "Товар успешно удалён!",
            "produto.selecionar": "Выберите товар из списка.",
            "produto.nao_encontrado": "Товар не найден.",
            "produto.problemas": "Ошибка при удалении товара",
            "produto.selecione_fornecedor": "Выберите поставщика.",

            # Экран Пользователей
            "usuario.janela_titulo": "Управление пользователями",
            "usuario.titulo": "Регистрация пользователя",
            "usuario.dados_frame": "Данные пользователя",
            "usuario.email": "Эл. почта:",
            "usuario.data_nascimento": "Дата рождения (ДД/ММ/ГГГГ):",
            "usuario.estado": "Штат:",
            "usuario.cidade": "Город:",
            "usuario.perfil": "Профиль:",
            "usuario.coluna_email": "Эл. почта",
            "usuario.coluna_nascimento": "Дата рождения",
            "usuario.coluna_idade": "Возраст",
            "usuario.coluna_cidade": "Город",
            "usuario.coluna_uf": "Штат",
            "usuario.coluna_perfil": "Профиль",
            "usuario.confirmar_exclusao": "Вы действительно хотите удалить этого пользователя?",
            "usuario.cadastrado_sucesso": "Пользователь успешно зарегистрирован!",
            "usuario.atualizado_sucesso": "Пользователь успешно обновлён!",
            "usuario.excluido_sucesso": "Пользователь успешно удалён!",
            "usuario.selecionar": "Выберите пользователя из списка.",
            "usuario.nao_encontrado": "Пользователь не найден.",
            "usuario.problemas": "Ошибка при удалении пользователя",
            "usuario.erro_data_invalida": "Неверная дата рождения. Используйте формат ДД/ММ/ГГГГ.",
            "usuario.erro_selecionar_cidade": "Выберите город.",
            "usuario.erro_selecionar_perfil": "Выберите профиль.",
        },

        
    }

    @classmethod
    def definir(cls, codigo):
        cls.ATUAL = codigo

    @classmethod
    def t(cls, chave):
        return cls.TEXTOS[cls.ATUAL].get(chave, chave)
    
Idioma.definir("es")